serviceAccount: 820070072100-compute@developer.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node:20.13.1
    entrypoint: npm
    args: ["install"]
  - name: node:20.13.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "MY_SECRET_KEY=${_MY_SECRET_KEY}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
