steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/condyte-mvp-v1/github.com/candooit/condyteplatform-ts:$COMMIT_SHA"
      - "-f"
      - "dockerfile"
      - "."
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/condyte-mvp-v1/github.com/candooit/condyteplatform-ts:$COMMIT_SHA"
