import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/components/providers/session-provider";
import QueryClientProvider from "@/components/providers/query-client-provider";
import { ClientSidebarWrapper } from "@/components/clients/sidebar-client";
import NextTopLoader from "nextjs-toploader";
import OnAuth from "@/components/etc/onAuth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <QueryClientProvider>
            <ClientSidebarWrapper>
              <NextTopLoader color="black" showSpinner={false} />
              <OnAuth />
              {children}
            </ClientSidebarWrapper>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
